"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
show_always = true
format = '[$user](bold green) '

[character]
success_symbol = '[❯❯❯](bold green)'
error_symbol   = '[❯❯❯](bold red)'

[cmd_duration]
format = '[󰔟 $duration]($style)'

[git_branch]
symbol = ' '
